### ISSUE TITLE
Column encryption using always encrypted fails for tables with clustered index when using online approach

### ISSUE THREAD

**Issue by DBarmanMS** [microsoft/SQLServerPSModule#34]
Repro steps:

1. Create a table with a clustered index
2. Try to encrypt a column in this table using UseOnlineApproach
3. The encryption fails with the error similar to "Set-SqlColumnEncryption: Cannot create more than one clustered index on table 'HR.tmp_ms_xx_xxxxxxxxxxxxx'. Drop the existing clustered index 'tmp_ms_xx_index_CIX_EmpDetails_EmpId1' before creating another."

PR - https://msdata.visualstudio.com/SQLToolsAndLibraries/_git/AlwaysEncrypted/pullrequest/1054777

**Comment by Matteo-T** [comment]
This was fixed in v22.1.1
