### ISSUE TITLE
Module does not appear to contain Start/Stop-SqlInstance Commands

### ISSUE THREAD

**Issue by bbseal** [microsoft/SQLServerPSModule#48]
Hi,

I've installed version 22.0.59 of this module, and I can't seem to use the `Start-SqlInstance` or `Stop-SqlInstance` commands.  They are in the module manifest, but when I go to use them, PowerShell says they aren't recognized.  `Get-SqlInstance` and many other commands in the module seem to work fine.

Here's a [screenshot](https://imgur.com/a/DrKG8uV).

**Comment by Matteo-T** [comment]
Hi @bbseal,
As per https://github.com/microsoft/SQLServerPSModule/wiki/What's-new-in-v22#relevant-changes-in-v22-compared-to-v21, those 2 cmdlets were removed as part of a major cleanup I did in v22.

Thanks for pointing out that I forgot to remove them from the manifest. I'll look into removing it in a future v22 update.

**Comment by Matteo-T** [comment]
This was fixed in v22.1.1.
