### ISSUE TITLE
Write-SqlTableData doesn't clear Write-Progress bar

### ISSUE THREAD

**Issue by samplesty** [microsoft/SQLServerPSModule#75]
Writing data to a table with Write-SqlTableData creates permanent Write-Progress bars that never clear. There is likely a missing call to Write-Progress with the -Complete flag in order to close out the bar. Also the bar never seems to fill to 100% despite the text status reporting 100%.

**Comment by Matteo-T** [comment]
hi @samplesty - I'll try to take a look as soon as I have a chance.

**Comment by Matteo-T** [comment]
Hi @samplesty,

It's indeed a bug (or two). Thanks for reporting it.

Now, it looks a lot better:

This is what I get (after the fix) in PS5.1:
![image](https://github.com/microsoft/SQLServerPSModule/assets/19174408/0e049f9b-7c0a-4176-9b44-7018e3243b4d)

This is what I get (after the fix) in PS7 (7.4.3):
![image](https://github.com/microsoft/SQLServerPSModule/assets/19174408/307231be-c893-454b-8913-49e90c88b648)

If all goes well, this fix should roll into the upcoming v22.3.x version of the module.

**Comment by Matteo-T** [comment]
Fixed in v22.3.0 - or at least improved. Let me know what you think...
