### ISSUE TITLE
Question: Version 22.2 Release Notes Aren't Yet Populated

### ISSUE THREAD

**Issue by Delamater** [microsoft/SQLServerPSModule#78]
Hello, 

Regarding the release, v22.2.0: 
- https://www.powershellgallery.com/packages/SqlServer/22.2.0
- At the moment, nearly 64 million downloads

When I check the wiki for the release notes, they are empty. Do you plan to update those soon?
https://github.com/microsoft/SQLServerPSModule/wiki/What's-new-in-v22.2

Thanks in advance

**Comment by Matteo-T** [comment]
22.2 was a relatively small release, but you are right: I forgot to update it. I'll see aht I can do about it.

**Comment by Matteo-T** [comment]
Done.
