### ISSUE TITLE
Support all credential types for Add-SqlAzureAuthenticationContext

### ISSUE THREAD

**Issue by sejagada** [microsoft/SQLServerPSModule#81]
Currently, Add-SqlAzureAuthenticationContext supports only interactive browser login. 
We would be supporting all credential types supported by [DefaultAzureCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) - 
[EnvironmentCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet)
[WorkloadIdentityCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.workloadidentitycredential?view=azure-dotnet)
[ManagedIdentityCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet)
[SharedTokenCacheCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.sharedtokencachecredential?view=azure-dotnet)
[VisualStudioCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.visualstudiocredential?view=azure-dotnet)
[VisualStudioCodeCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.visualstudiocodecredential?view=azure-dotnet)
[AzureCliCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.azureclicredential?view=azure-dotnet)
[AzurePowerShellCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.azurepowershellcredential?view=azure-dotnet)
[AzureDeveloperCliCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.azuredeveloperclicredential?view=azure-dotnet)
[InteractiveBrowserCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.interactivebrowsercredential?view=azure-dotnet)

_Example 1:_ 
**Add-SqlAzureAuthenticationContext -DefaultAzureCredential**
This command acquires token using the following credential types, if enabled, will be tried, in order: EnvironmentCredential, WorkloadIdentityCredential, ManagedIdentityCredential, SharedTokenCacheCredential, VisualStudioCredential, VisualStudioCodeCredential, AzureCliCredential, AzurePowerShellCredential, AzureDeveloperCliCredential, InteractiveBrowserCredential.

_Example 2:_
Users will have option to exclude a credential type. For instance, if users do not want to include VisualStudioCredential & AzureDeveloperCliCredential while using DefaultAzureCredential, they can specify the cmdlet parameters as below.

**Add-SqlAzureAuthenticationContext -DefaultAzureCredential -ExcludeCredentials  VisualStudioCredential, AzureDeveloperCliCredential**

_Example 3:_
Users cannot exclude all the credential types. Specifying all exclude credential options would result in an exception - **"Add-SqlAzureAuthenticationContext: At least one credential type must be allowed when using the -DefaultAzureCredential parameter."**

**Add-SqlAzureAuthenticationContext -DefaultAzureCredential -ExcludeCredentials EnvironmentCredential, WorkloadIdentityCredential, ManagedIdentityCredential, SharedTokenCacheCredential, VisualStudioCredential, VisualStudioCodeCredential, AzureCliCredential, AzurePowerShellCredential, AzureDeveloperCliCredential, InteractiveBrowserCredential**

**Comment by Matteo-T** [comment]
Fixed in v22.3.0
