### ISSUE TITLE
Add parameter to allow verbose logging for Set-SqlColumnEncryption cmdlet

### ISSUE THREAD

**Issue by sejagada** [microsoft/SQLServerPSModule#85]
Currently, it becomes hard to reproduce and diagnose issues faced by customers while performing column encryption, decryption or re-encryption using the 'Set-SqlColumnEncryption' cmdlet. We are introducing a parameter 'AllowVerboseLogging' (similar to the 'Enable Verbose Logging' check-box in SSMS AE Wizard) for the 'Set-SqlColumnEncryption' cmdlet. On specifying this parameter, 
- Some verbose messages are logged to the log file
- The dacpac files used by the internal libraries to perform the encryption / decryption / re-encryption are retained instead of getting deleted post operation. The paths of the dacpac files are logged in the log file.

The dacpac files do not contain any table data and can be used to reproduce issues faced by customers and also generate diagnostics traces (using SqlPackage), which can help diagnose issues.

**Comment by Matteo-T** [comment]
@santoshkumarpadhy is working on this one, which should roll out in v22.3.x.
